### ISSUE TITLE
Treeshaking is not supported

### ISSUE THREAD

**Issue by maxswjeon** [MKAbuMattar/devicons-react#102]
I'm using this notation to import icons to my vite project

```ts
import {
	Css3OriginalWordmark,
	Html5OriginalWordmark,
	JavascriptOriginal,
	PhpOriginal,
	TypescriptOriginal,
} from "devicons-react";
```

It results adding ALL icons in my bundle

(Visualized with [vite-bundle-analyzer](https://www.npmjs.com/package/vite-bundle-visualizer))
![image](https://github.com/MKAbuMattar/devicons-react/assets/10355032/eb389407-1558-4d4f-b7fa-12bc17b8ff56)

Please support tree shaking. Thanks.

**Comment by MKAbuMattar** [comment]
try using

this to import what u need

```tsx
import Css3OriginalWordmark from 'devicons-react/lib/icons/Css3OriginalWordmark';
import Html5OriginalWordmark from 'devicons-react/lib/icons/Html5OriginalWordmark';
import JavascriptOriginal from 'devicons-react/lib/icons/JavascriptOriginal';
import PhpOriginal from 'devicons-react/lib/icons/PhpOriginal';
import TypescriptOriginal from 'devicons-react/lib/icons/TypescriptOriginal';
```
