### ISSUE TITLE
Relevant Icons are missing

### ISSUE THREAD

**Issue by sadkebab** [MKAbuMattar/devicons-react#81]
I was building my portfolio and so far this was the best devicon library I found, but unfortunately icons for some relevant technologies are missing like Solid.js, DynamoDB, Tauri, and so on.
i think an update would be great!

**Comment by sadkebab** [comment]
I just realized that most of those are actually in the beta release, ignore this 😫

**Comment by MKAbuMattar** [comment]
The beta version has most icons but is not stable, and there is an awesome project for the AWS Icons.

devicons-react@beta > https://devicons-react.vercel.app/beta
awsicons >
github: https://github.com/boyney123/awsicons
website: https://awsicons.dev/
